# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 16, 40, 21, 71716, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 16, 40, 21, 72203, tzinfo=utc)),
        ),
    ]
