# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171119_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 17, 6, 39, 958688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pdfurl',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 17, 6, 39, 959138, tzinfo=utc)),
        ),
    ]
