# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171119_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 21, 17, 43, 31290, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pdfurl',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 21, 17, 43, 31738, tzinfo=utc)),
        ),
    ]
