# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171119_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 22, 47, 25, 246768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pdfurl',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 22, 47, 25, 247434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pdfurl',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file', related_query_name='pdf_file', to='api.PDFFile'),
        ),
    ]
